name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: thakyZ/MyDalamudPlugins/.github/workflows/reusable_create_release.yml@main
    with:
      internal_name: EmoteCmdComplex
      solution_name: EmoteCmdComplex
      build_configuration: Release
      personal_plugin_repo: thakyZ/MyDalamudPlugins
      personal_plugin_repo_branch: main
    secrets: inherit